language : python

python:
  - "2.7"

sudo: required

before_install:
  - curl --output /usr/local/bin/phantomjs https://s3.amazonaws.com/circle-downloads/phantomjs-2.1.1
  
install:
  - pip install coveralls

script:
  - coverage run --source=pyinsta_dl setup.py test

after_success:
  - coveralls

#
