language : python

python:
  - "2.7"

sudo: required

before_install:
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -jxvf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - mv phantomjs-2.1.1-linux-x86_64 /usr/local/share/phantomjs-2.1.1-linux-x86_64

install:
  - pip install coveralls

script:
  - coverage run --source=pyinsta_dl setup.py test

after_success:
  - coveralls